server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resource-server:
        jwt:
          secret: ${SECRET_KEY}
          expiration: 900000      # 15 mins
          refresh-expiration: 604800000 # 7 days

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.example.cnpmnc.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json